"""Explicit handler declarations; adding a group needs no runtime branch."""
from solution_runner.pipelines.core.handlers import HandlerSpec

HANDLERS = (
    HandlerSpec('exponential-26650-common-base-affine-exponent', 'solution_runner.pipelines.equations.group_26650:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('exponential-77379-equal-exponent-different-bases', 'solution_runner.pipelines.equations.group_77379:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('logarithm-common-normalized', 'solution_runner.pipelines.equations.group_26646:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('logarithm-77381-shifted-equal-logs', 'solution_runner.pipelines.equations.group_77381:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('logarithm-77382-affine-base-perfect-power', 'solution_runner.pipelines.equations.group_77382:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('logarithm-315120-power-argument-common-base', 'solution_runner.pipelines.equations.group_315120:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('logarithm-315535-exponential-logarithm-affine', 'solution_runner.pipelines.equations.group_315535:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('trigonometric-table-value-affine-argument', 'solution_runner.pipelines.equations.group_trigonometric:build_context_repair_plan', requires_parent_condition_asset=False, asset_selector='solution_runner.pipelines.equations.group_trigonometric:required_assets'),
    HandlerSpec('elementary-equations-509214-linear-equation', 'solution_runner.pipelines.equations.group_509214_planner:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-square-root-selector', 'solution_runner.pipelines.equations.group_square_root_selector:build_context_repair_plan', requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-101879-equal-numerators', 'solution_runner.pipelines.equations.group_101879_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-26662-fractional-linear-equation', 'solution_runner.pipelines.equations.group_26662_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-26663-negative-fractional-linear-equation', 'solution_runner.pipelines.equations.group_26663_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-26667-quadratic-root-selector', 'solution_runner.pipelines.equations.group_26667_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-282849-shifted-cube-root', 'solution_runner.pipelines.equations.group_282849_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-282850-odd-power-root', 'solution_runner.pipelines.equations.group_282850_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-315119-equal-unit-fractions', 'solution_runner.pipelines.equations.group_315119_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77366-rational-square-root-selector', 'solution_runner.pipelines.equations.group_77366_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77367-rational-quadratic-selector', 'solution_runner.pipelines.equations.group_77367_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77368-equal-squares-first-solution', 'solution_runner.pipelines.equations.group_77368_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77369-completed-square', 'solution_runner.pipelines.equations.group_77369_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77370-expanded-square-linear', 'solution_runner.pipelines.equations.group_77370_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77371-fractional-square-root', 'solution_runner.pipelines.equations.group_77371_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('elementary-equations-77383-reciprocal-linear', 'solution_runner.pipelines.equations.group_77383_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html'), ('current_asset_content_type', 'current_asset_content_type')), requires_parent_condition_asset=False),
    HandlerSpec('irrational-26656-square-root-affine', 'solution_runner.pipelines.equations.group_26656:build_context_repair_plan',
        requires_parent_condition_asset=False),
    HandlerSpec('irrational-511751-reciprocal-square-root', 'solution_runner.pipelines.equations.group_511751:build_context_repair_plan',
        requires_parent_condition_asset=False),
    HandlerSpec('irrational-26660-square-root-rational-affine', 'solution_runner.pipelines.equations.group_26660:build_context_repair_plan',
        requires_parent_condition_asset=False),
    HandlerSpec('irrational-26668-square-root-negative-x', 'solution_runner.pipelines.equations.group_26668:build_context_repair_plan',
        requires_parent_condition_asset=False),
    HandlerSpec('irrational-27466-odd-root-affine', 'solution_runner.pipelines.equations.group_27466:build_context_repair_plan',
        requires_parent_condition_asset=False),
)
