"""Explicit handler declarations; adding a group needs no runtime branch."""
from solution_runner.pipelines.core.handlers import HandlerSpec

HANDLERS = (
    HandlerSpec('general-triangle-27591-area-sas-30', 'solution_runner.pipelines.triangles.general.planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html')), parent_from_group_listing=True, expected_parent_id='79ac61c1-1e29-4010-b3a5-22a628bb98d6', strict_frozen_input=True, requires_frozen_manifest=True, manifest_validator='solution_runner.pipelines.triangles.general.scope_27591:validate_manifest'),
    HandlerSpec('general-triangle-27592-midline-area', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27592-midline-area'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27623-altitude-area-ratio', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27623-altitude-area-ratio'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27743-exterior-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27743-exterior-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27752-angle-ratio', 'solution_runner.pipelines.triangles.general.ratio_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_html', 'parent_solution_html')), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27757-altitude-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27757-altitude-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27758-bisector-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27758-bisector-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27759-bisector-exterior-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27759-bisector-exterior-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27762-orthocenter-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27762-orthocenter-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27763-altitudes-angle-sum', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27763-altitudes-angle-sum'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27764-incenter-angle', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27764-incenter-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27767-altitude-bisector-intersection', 'solution_runner.pipelines.triangles.general.angle_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id')), options=(('rule', 'general-triangle-27767-altitude-bisector-intersection'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27768-bisector-equal-segments-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27768-bisector-equal-segments-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27769-extension-isosceles-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27769-extension-isosceles-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27776-bisector-congruent-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27776-bisector-congruent-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27777-exterior-bisector-isosceles-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27777-exterior-bisector-isosceles-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27778-incenter-bisectors-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27778-incenter-bisectors-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-27779-orthocenter-altitudes-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-27779-orthocenter-altitudes-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-317337-midline-small-area-to-total', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-317337-midline-small-area-to-total'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-319058-midline-trapezoid-area', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-319058-midline-trapezoid-area'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-500142-altitudes-obtuse-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-500142-altitudes-obtuse-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-510796-extended-altitudes-angle', 'solution_runner.pipelines.triangles.general.next_group_planner:build_repair_plan',
        inputs=(('parent_solution_html', 'parent_solution_html'), ('parent_condition_asset_id', 'parent_asset_id'), ('parent_solution_assets', 'parent_solution_assets')), options=(('rule', 'general-triangle-510796-extended-altitudes-angle'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-561168-obtuse-included-angle-area', 'solution_runner.pipelines.triangles.general.group_561168_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'),), parent_from_group_listing=True),
    HandlerSpec('general-triangle-681454-bisector-angle', 'solution_runner.pipelines.triangles.general.group_681454_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'),), parent_from_group_listing=True),
)
