"""Explicit handler declarations; adding a group needs no runtime branch."""
from solution_runner.pipelines.core.handlers import HandlerSpec

HANDLERS = (
    HandlerSpec('right-triangle-642289-sine-opposite', 'solution_runner.pipelines.triangles.right.group_642289_planner:build_repair_plan',
        inputs=(('parent_condition_asset_id', 'parent_asset_id'),)),
    HandlerSpec('right-triangle-acute-angle-difference', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-acute-angle-difference'),)),
    HandlerSpec('right-triangle-acute-angle-ratio', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-acute-angle-ratio'),)),
    HandlerSpec('right-triangle-altitude-bisector-angle', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-altitude-bisector-angle'),)),
    HandlerSpec('right-triangle-altitude-bisector-inverse', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-altitude-bisector-inverse'),)),
    HandlerSpec('right-triangle-altitude-length', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-altitude-length'),)),
    HandlerSpec('right-triangle-altitude-line-angle', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-altitude-line-angle'),)),
    HandlerSpec('right-triangle-altitude-median-inverse', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-altitude-median-inverse'),)),
    HandlerSpec('right-triangle-altitude-universal', 'solution_runner.pipelines.triangles.right.planner:build_altitude_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),)),
    HandlerSpec('right-triangle-area-leg-difference', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-area-leg-difference'),)),
    HandlerSpec('right-triangle-bisector-intersection-angle', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-bisector-intersection-angle'),)),
    HandlerSpec('right-triangle-bisector-median-angle', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-bisector-median-angle'),)),
    HandlerSpec('right-triangle-bisector-median-inverse', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-bisector-median-inverse'),)),
    HandlerSpec('right-triangle-cosine-hypotenuse', 'solution_runner.pipelines.triangles.right.planner:build_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('required_trig_name', 'cos'), ('required_requested', 'AB')), constraints=(('required_trig_name', 'cos'), ('required_requested', 'AB'))),
    HandlerSpec('right-triangle-hypotenuse-projection-ah', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-hypotenuse-projection-ah'),)),
    HandlerSpec('right-triangle-hypotenuse-projection-bh', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-hypotenuse-projection-bh'),)),
    HandlerSpec('right-triangle-leg-hypotenuse-area', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-leg-hypotenuse-area'),)),
    HandlerSpec('right-triangle-median-angle', 'solution_runner.pipelines.triangles.right.planner:build_elementary_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('content_rule_key', 'right-triangle-median-angle'),)),
    HandlerSpec('right-triangle-sine', 'solution_runner.pipelines.triangles.right.planner:build_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),)),
    HandlerSpec('right-triangle-tangent-hypotenuse', 'solution_runner.pipelines.triangles.right.planner:build_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),), options=(('required_trig_name', 'tg'), ('required_requested', 'AB')), constraints=(('required_trig_name', 'tg'), ('required_requested', 'AB'))),
    HandlerSpec('right-triangle-tangent-opposite-cathetus', 'solution_runner.pipelines.triangles.right.planner:build_tangent_bc_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),)),
    HandlerSpec('right-triangle-universal', 'solution_runner.pipelines.triangles.right.planner:build_universal_repair_plan',
        inputs=(('parent_asset_id', 'parent_asset_id'),)),
)
